apiVersion: 1
datasources:
  - name: SignalsPostgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
